<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Pruebas de login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>23ca7ab4-706d-4fb4-bbb0-0f0d129a297a</testSuiteGuid>
   <testCaseLink>
      <guid>77e627b9-3767-4528-b4ae-c49c939336ec</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Web reserva de citas/Formulario de Login/Login Autogenerado</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>ea6be3e2-88fb-45c6-9b5b-2cd8a367d080</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Web reserva de citas/Formulario de Login/Login con usuario correccto</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad106b53-b496-4e2d-9d2f-8561ae900294</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48f342f9-da47-429f-a08a-7a1cc9259d6b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7bc72118-601c-4af7-bc39-fab019178eb4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Web reserva de citas/Formulario de Login/Login con usuario incorrecto</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44f04352-a3a4-4c8e-97f5-6d792506a8d6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>977ea591-93c8-42fc-8239-a0e7939c1910</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
