<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Botón de logout</name>
   <tag></tag>
   <elementGuidId>98fa14d9-5048-407a-8be1-07e53f874f8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Logout')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//a[contains(text(),'Logout')]</value>
      <webElementGuid>58171fd5-e4cc-4bb0-b3dd-7bdfc3781f51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;sidebar-wrapper&quot;]/ul/li[5]/a</value>
      <webElementGuid>2faac8e1-6521-41d9-ab19-203fd3d3eb53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
